export = {
  riff: {
    size: 1262828,
  },
  format: {
    riff: {
      size: 1262828,
    },
    chunks: [
      {
        type: "VP8X",
        offset: 12,
        size: 18,
        width: 200,
        height: 200,
        icc: false,
        alpha: true,
        exif: false,
        xmp: true,
        animation: true,
        bitstream: {
          rsv1: 0,
          icc: 0,
          alpha: 1,
          exif: 0,
          xmp: 1,
          animation: 1,
          rsv2: 0,
          rsv3: 0,
          canvasWidth: 200,
          canvasHeight: 200,
        },
      },
      {
        type: "ANIM",
        offset: 30,
        size: 14,
        backgroundColor: {
          r: 255,
          g: 237,
          b: 181,
          a: 255,
        },
        loop: Infinity,
        bitstream: {
          backgroundColor: {
            r: 255,
            g: 237,
            b: 181,
            a: 255,
          },
          loopCount: 0,
        },
      },
      {
        type: "ANMF",
        offset: 44,
        size: 13426,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 13470,
        size: 9850,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 23320,
        size: 9918,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 33238,
        size: 9908,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 43146,
        size: 9934,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 53080,
        size: 13576,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 66656,
        size: 9948,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 76604,
        size: 9760,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 86364,
        size: 9844,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 96208,
        size: 13622,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 109830,
        size: 9696,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 119526,
        size: 9598,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 129124,
        size: 9504,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 138628,
        size: 9448,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 148076,
        size: 9322,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 157398,
        size: 13518,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 170916,
        size: 9534,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 180450,
        size: 9608,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 190058,
        size: 9620,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 199678,
        size: 9862,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 209540,
        size: 13524,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 223064,
        size: 9806,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 232870,
        size: 9908,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 242778,
        size: 9888,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 252666,
        size: 9956,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 262622,
        size: 13226,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 275848,
        size: 9862,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 285710,
        size: 9788,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 295498,
        size: 9684,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 305182,
        size: 13100,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 318282,
        size: 9478,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 327760,
        size: 9358,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 337118,
        size: 9346,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 346464,
        size: 9190,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 355654,
        size: 9280,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 364934,
        size: 13112,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 378046,
        size: 9542,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 387588,
        size: 9444,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 397032,
        size: 9568,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 406600,
        size: 9632,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 416232,
        size: 13426,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 429658,
        size: 9850,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 439508,
        size: 9918,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 449426,
        size: 9908,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 459334,
        size: 9934,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 469268,
        size: 13576,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 482844,
        size: 9948,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 492792,
        size: 9760,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 502552,
        size: 9844,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 512396,
        size: 13622,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 526018,
        size: 9696,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 535714,
        size: 9598,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 545312,
        size: 9504,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 554816,
        size: 9448,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 564264,
        size: 9322,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 573586,
        size: 13518,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 587104,
        size: 9534,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 596638,
        size: 9608,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 606246,
        size: 9620,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 615866,
        size: 9862,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 625728,
        size: 13524,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 639252,
        size: 9806,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 649058,
        size: 9908,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 658966,
        size: 9888,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 668854,
        size: 9956,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 678810,
        size: 13226,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 692036,
        size: 9862,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 701898,
        size: 9788,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 711686,
        size: 9684,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 721370,
        size: 13100,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 734470,
        size: 9478,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 743948,
        size: 9358,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 753306,
        size: 9346,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 762652,
        size: 9190,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 771842,
        size: 9280,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 781122,
        size: 13112,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 794234,
        size: 9542,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 803776,
        size: 9444,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 813220,
        size: 9568,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 822788,
        size: 9632,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 832420,
        size: 13426,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 845846,
        size: 9850,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 855696,
        size: 9918,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 865614,
        size: 9908,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 875522,
        size: 9934,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 885456,
        size: 13576,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 899032,
        size: 9948,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 908980,
        size: 9760,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 918740,
        size: 9844,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 928584,
        size: 13622,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 942206,
        size: 9696,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 951902,
        size: 9598,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 961500,
        size: 9504,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 971004,
        size: 9448,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 980452,
        size: 9322,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 989774,
        size: 13518,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 1003292,
        size: 9534,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 1012826,
        size: 9608,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 1022434,
        size: 9620,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 1032054,
        size: 9862,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 1041916,
        size: 13524,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 1055440,
        size: 9806,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 1065246,
        size: 9908,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 1075154,
        size: 9888,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 1085042,
        size: 9956,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 1094998,
        size: 13226,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 1108224,
        size: 9862,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 1118086,
        size: 9788,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 1127874,
        size: 9684,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 1137558,
        size: 13100,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 1150658,
        size: 9478,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 1160136,
        size: 9358,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 1169494,
        size: 9346,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 1178840,
        size: 9190,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 1188030,
        size: 9280,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 1197310,
        size: 13112,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 1210422,
        size: 9542,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 1219964,
        size: 9444,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 1229408,
        size: 9568,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 1238976,
        size: 9632,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 1248608,
        size: 13426,
        width: 200,
        height: 200,
        duration: 30,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 30,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "XMP",
        offset: 1262034,
        size: 794,
      },
    ],
    summary: {
      frames: 121,
      chunks: {
        VP8: 0,
        VP8L: 0,
        VP8X: 1,
        ALPH: 0,
        ANIM: 1,
        ANMF: 121,
        ICCP: 0,
        EXIF: 0,
        XMP: 1,
      },
    },
  },
};
