export = {
  riff: {
    size: 327672,
  },
  format: {
    riff: {
      size: 327672,
    },
    chunks: [
      {
        type: "VP8X",
        format: "extended",
        offset: 12,
        size: 18,
        width: 200,
        height: 200,
        icc: false,
        alpha: true,
        exif: false,
        xmp: true,
        animation: true,
        bitstream: {
          rsv1: 0,
          icc: 0,
          alpha: 1,
          exif: 0,
          xmp: 1,
          animation: 1,
          rsv2: 0,
          rsv3: 0,
          canvasWidth: 200,
          canvasHeight: 200,
        },
      },
      {
        type: "ANIM",
        offset: 30,
        size: 14,
        backgroundColor: {
          r: 101,
          g: 36,
          b: 68,
          a: 255,
        },
        loop: Infinity,
        bitstream: {
          backgroundColor: {
            r: 101,
            g: 36,
            b: 68,
            a: 255,
          },
          loopCount: 0,
        },
      },
      {
        type: "ANMF",
        offset: 44,
        size: 6444,
        width: 200,
        height: 200,
        duration: 70,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 70,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 6488,
        size: 6606,
        width: 200,
        height: 200,
        duration: 70,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 70,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 13094,
        size: 6252,
        width: 200,
        height: 200,
        duration: 70,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 70,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 19346,
        size: 6646,
        width: 200,
        height: 200,
        duration: 70,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 70,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 25992,
        size: 6748,
        width: 200,
        height: 200,
        duration: 70,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 70,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 32740,
        size: 6542,
        width: 200,
        height: 200,
        duration: 70,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 70,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 39282,
        size: 6218,
        width: 200,
        height: 200,
        duration: 70,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 70,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 45500,
        size: 6602,
        width: 200,
        height: 200,
        duration: 70,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 70,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 52102,
        size: 6552,
        width: 200,
        height: 200,
        duration: 70,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 70,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 58654,
        size: 6608,
        width: 200,
        height: 200,
        duration: 70,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 70,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 65262,
        size: 6234,
        width: 200,
        height: 200,
        duration: 70,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 70,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 71496,
        size: 6284,
        width: 200,
        height: 200,
        duration: 70,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 70,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 77780,
        size: 6366,
        width: 200,
        height: 200,
        duration: 70,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 70,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 84146,
        size: 6374,
        width: 200,
        height: 200,
        duration: 70,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 70,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 90520,
        size: 6512,
        width: 200,
        height: 200,
        duration: 70,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 70,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 97032,
        size: 6478,
        width: 200,
        height: 200,
        duration: 70,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 70,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 103510,
        size: 6422,
        width: 200,
        height: 200,
        duration: 70,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 70,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 109932,
        size: 6314,
        width: 200,
        height: 200,
        duration: 70,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 70,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 116246,
        size: 6228,
        width: 200,
        height: 200,
        duration: 70,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 70,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 122474,
        size: 6286,
        width: 200,
        height: 200,
        duration: 70,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 70,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 128760,
        size: 6336,
        width: 200,
        height: 200,
        duration: 70,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 70,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 135096,
        size: 6300,
        width: 200,
        height: 200,
        duration: 70,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 70,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 141396,
        size: 6474,
        width: 200,
        height: 200,
        duration: 70,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 70,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 147870,
        size: 6546,
        width: 200,
        height: 200,
        duration: 70,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 70,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 154416,
        size: 6536,
        width: 200,
        height: 200,
        duration: 70,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 70,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 160952,
        size: 6194,
        width: 200,
        height: 200,
        duration: 70,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 70,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 167146,
        size: 6330,
        width: 200,
        height: 200,
        duration: 70,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 70,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 173476,
        size: 6386,
        width: 200,
        height: 200,
        duration: 70,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 70,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 179862,
        size: 6126,
        width: 200,
        height: 200,
        duration: 70,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 70,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 185988,
        size: 6342,
        width: 200,
        height: 200,
        duration: 70,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 70,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 192330,
        size: 6434,
        width: 200,
        height: 200,
        duration: 70,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 70,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 198764,
        size: 6484,
        width: 200,
        height: 200,
        duration: 70,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 70,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 205248,
        size: 6348,
        width: 200,
        height: 200,
        duration: 70,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 70,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 211596,
        size: 6192,
        width: 200,
        height: 200,
        duration: 70,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 70,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 217788,
        size: 6316,
        width: 200,
        height: 200,
        duration: 70,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 70,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 224104,
        size: 6076,
        width: 200,
        height: 200,
        duration: 70,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 70,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 230180,
        size: 6434,
        width: 200,
        height: 200,
        duration: 70,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 70,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 236614,
        size: 6672,
        width: 200,
        height: 200,
        duration: 70,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 70,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 243286,
        size: 6646,
        width: 200,
        height: 200,
        duration: 70,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 70,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 249932,
        size: 6316,
        width: 200,
        height: 200,
        duration: 70,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 70,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 256248,
        size: 6180,
        width: 200,
        height: 200,
        duration: 70,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 70,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 262428,
        size: 6506,
        width: 200,
        height: 200,
        duration: 70,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 70,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 268934,
        size: 6456,
        width: 200,
        height: 200,
        duration: 70,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 70,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 275390,
        size: 6512,
        width: 200,
        height: 200,
        duration: 70,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 70,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 281902,
        size: 6148,
        width: 200,
        height: 200,
        duration: 70,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 70,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 288050,
        size: 6478,
        width: 200,
        height: 200,
        duration: 70,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 70,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 294528,
        size: 6420,
        width: 200,
        height: 200,
        duration: 70,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 70,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 300948,
        size: 6356,
        width: 200,
        height: 200,
        duration: 70,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 70,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 307304,
        size: 6528,
        width: 200,
        height: 200,
        duration: 70,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 70,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 313832,
        size: 6472,
        width: 200,
        height: 200,
        duration: 70,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 70,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "ANMF",
        offset: 320304,
        size: 6574,
        width: 200,
        height: 200,
        duration: 70,
        offsetX: 0,
        offsetY: 0,
        dispose: 0,
        blend: 0,
        bitstream: {
          offsetX: 0,
          offsetY: 0,
          width: 200,
          height: 200,
          duration: 70,
          rsv1: 0,
          blending: 0,
          disposal: 0,
        },
      },
      {
        type: "XMP",
        offset: 326878,
        size: 794,
      },
    ],
    summary: {
      isAnimated: true,
      isLossless: false,
      hasAlpha: true,
      width: 200,
      height: 200,
      frames: 51,
      chunks: {
        VP8: 0,
        VP8L: 0,
        VP8X: 1,
        ALPH: 0,
        ANIM: 1,
        ANMF: 51,
        ICCP: 0,
        EXIF: 0,
        XMP: 1,
      },
    },
  },
};
