export = {
  riff: {
    size: 303658,
  },
  format: {
    riff: {
      size: 303658,
    },
    chunks: [
      {
        type: "VP8X",
        offset: 12,
        size: 18,
        width: 960,
        height: 640,
        icc: false,
        alpha: false,
        exif: true,
        xmp: false,
        animation: false,
        bitstream: {
          rsv1: 0,
          icc: 0,
          alpha: 0,
          exif: 1,
          xmp: 0,
          animation: 0,
          rsv2: 0,
          rsv3: 0,
          canvasWidth: 960,
          canvasHeight: 640,
        },
      },
      {
        type: "VP8",
        format: "lossy",
        offset: 30,
        size: 255988,
        width: 960,
        height: 640,
        bitstream: {
          keyframe: 0,
          version: 0,
          showFrame: 1,
          firstPartSize: 12930,
          width: 960,
          horizontalScale: 0,
          height: 640,
          verticalScale: 0,
        },
      },
      {
        type: "EXIF",
        offset: 256018,
        size: 47640,
      },
    ],
    summary: {
      frames: 1,
      chunks: {
        VP8: 1,
        VP8L: 0,
        VP8X: 1,
        ALPH: 0,
        ANIM: 0,
        ANMF: 0,
        ICCP: 0,
        EXIF: 1,
        XMP: 0,
      },
    },
  },
};
