export = {
  riff: {
    size: 10996,
  },
  format: {
    riff: {
      size: 10996,
    },
    chunks: [
      {
        type: "VP8X",
        format: "extended",
        offset: 12,
        size: 18,
        width: 22,
        height: 460,
        icc: true,
        alpha: false,
        exif: true,
        xmp: true,
        animation: false,
        bitstream: {
          rsv1: 0,
          icc: 1,
          alpha: 0,
          exif: 1,
          xmp: 1,
          animation: 0,
          rsv2: 0,
          rsv3: 0,
          canvasWidth: 22,
          canvasHeight: 460,
        },
      },
      {
        type: "ICCP",
        offset: 30,
        size: 3152,
      },
      {
        type: "VP8L",
        format: "lossless",
        offset: 3182,
        size: 2512,
        width: 22,
        height: 460,
        alpha: false,
        bitstream: {
          width: 22,
          height: 460,
          alpha: 0,
          version: 0,
        },
      },
      {
        type: "EXIF",
        offset: 5694,
        size: 938,
      },
      {
        type: "XMP",
        offset: 6632,
        size: 4364,
      },
    ],
    summary: {
      isAnimated: false,
      isLossless: true,
      hasAlpha: false,
      width: 22,
      height: 460,
      frames: 1,
      chunks: {
        VP8: 0,
        VP8L: 1,
        VP8X: 1,
        ALPH: 0,
        ANIM: 0,
        ANMF: 0,
        ICCP: 1,
        EXIF: 1,
        XMP: 1,
      },
    },
  },
};
