export = {
  riff: {
    size: 18840,
  },
  format: {
    riff: {
      size: 18840,
    },
    chunks: [
      {
        type: "VP8X",
        format: "extended",
        offset: 12,
        size: 18,
        width: 400,
        height: 301,
        icc: false,
        alpha: true,
        exif: false,
        xmp: false,
        animation: false,
        bitstream: {
          rsv1: 0,
          icc: 0,
          alpha: 1,
          exif: 0,
          xmp: 0,
          animation: 0,
          rsv2: 0,
          rsv3: 0,
          canvasWidth: 400,
          canvasHeight: 301,
        },
      },
      {
        type: "ALPH",
        offset: 30,
        size: 3782,
        preprocessing: 0,
        filter: 0,
        compress: 1,
        bitstream: {
          rsv1: 0,
          preprocessing: 0,
          filtering: 0,
          compression: 1,
        },
      },
      {
        type: "VP8",
        format: "lossy",
        offset: 3812,
        size: 15028,
        width: 400,
        height: 301,
        bitstream: {
          keyframe: 0,
          version: 0,
          showFrame: 1,
          firstPartSize: 1948,
          width: 400,
          horizontalScale: 0,
          height: 301,
          verticalScale: 0,
        },
      },
    ],
    summary: {
      isAnimated: false,
      isLossless: false,
      hasAlpha: true,
      width: 400,
      height: 301,
      frames: 1,
      chunks: {
        VP8: 1,
        VP8L: 0,
        VP8X: 1,
        ALPH: 1,
        ANIM: 0,
        ANMF: 0,
        ICCP: 0,
        EXIF: 0,
        XMP: 0,
      },
    },
  },
};
